### ISSUE TITLE
[FEAT] - Proper Error system

### ISSUE THREAD

**Issue by j-dogcoder** [Heptagram-Bot-Project/discord-bot#364]
### What feature would you like to see?

Error handler based on [becca Lyria's error handler](https://github.com/BeccaLyria/discord-bot/)

### Additional information

A clearer version of #23 and #242

**Comment by aserputov** [comment]
Hey, @j-dogcoder. I would like to try this issue if you don't mind. Could you please assign it to me?

**Comment by j-dogcoder** [comment]
Sure!

**Comment by aserputov** [comment]
@j-dogcoder  do I still need to work on this issue ? or you planning to archive that project ?

**Comment by j-dogcoder** [comment]
> @j-dogcoder do I still need to work on this issue ? or you planning to archive that project ?

You should continue. @apoorvcodes is taking over.

**Comment by j-dogcoder** [comment]
Closed with #390
