### ISSUE TITLE
[FEAT] - New Warning System that works with Mongo

### ISSUE THREAD

**Issue by j-dogcoder** [Heptagram-Bot-Project/discord-bot#410]
### What feature would you like to see?

New Warning System that works with Mongo

**Comment by pritipsingh** [comment]
Do you still need help with this? If yes then please let me know.

**Comment by j-dogcoder** [comment]
> Do you still need help with this? If yes then please let me know.

Hey @pritipsingh, We would love your help!

**Comment by j-dogcoder** [comment]
Would you like me to assign it to you?

**Comment by pritipsingh** [comment]
Ya sure please. Also please let me know if you've any discord channel where I can ask my doubts and how to go about it?

**Comment by j-dogcoder** [comment]
Sure @pritipsingh! You can check out our [CONTRIBUTING.md](https://github.com/Heptagram-Bot-Project/bot/blob/main/CONTRIBUTING.md) for a guide on how to get started, and their is a link for the server there.

**Comment by pritipsingh** [comment]
Hey @j-dogcoder did you review the code?

**Comment by pritipsingh** [comment]
hey, @j-dogcoder Did you review the code? I made the required changes

**Comment by j-dogcoder** [comment]
Hey @pritipsingh! So sorry I haven't gotten to this yet. I will do that later today.
